- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache=true state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=installed
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  tags: packages

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  sudo_user: postgres
  postgresql_db: name=restplusdb
             encoding='UTF-8'
             lc_collate='en_US.UTF-8'
             lc_ctype='en_US.UTF-8'
             template='template0'
             state=present

- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user: db=restplusdb
               name=postgres
               password=postgres
               priv=ALL
               state=present

- name: add new configuration to "pg_hba.conf"
  shell: |
          bash -c 'cat<<EOF >> /etc/postgresql/9.5/main/pg_hba.conf
          host    all             all             0.0.0.0/0                md5
          host    all             all              ::/0                    md5
          EOF'
  become: yes
  become_method: sudo

- name: add new configuaration to "postgres.conf"
  shell: |
          bash -c "cat<<EOF >> /etc/postgresql/9.5/main/postgresql.conf
          listen_addresses = '*'
          EOF"
  become: yes
  become_method: sudo

- name: restart postgres
  shell: sudo /etc/init.d/postgresql restart